# Generated by Django 5.2.1 on 2025-05-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120)),
                ('Author', models.CharField(max_length=50)),
                ('Price', models.FloatField()),
                ('Publication_date', models.DateField()),
                ('Subject', models.TextField()),
                ('keyword', models.CharField()),
                ('Edition', models.DecimalField(decimal_places=5, max_digits=15)),
                ('Publisher', models.CharField()),
            ],
        ),
    ]
