# Generated by Django 5.2.1 on 2025-06-02 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('user_app', '0010_remove_customercreate_name_customercreate_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstructure',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bookstructure',
            name='Publisher',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='bookstructure',
            name='keyword',
            field=models.CharField(max_length=120),
        ),
        migrations.CreateModel(
            name='IssueBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120)),
                ('Price', models.FloatField()),
                ('Issue_date', models.DateField()),
                ('Return_date', models.DateField()),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.customercreate')),
            ],
        ),
    ]
