# Generated by Django 5.2.1 on 2025-06-03 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookstructure_count_alter_bookstructure_publisher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookstructure',
            name='count',
        ),
        migrations.RemoveField(
            model_name='issuebook',
            name='Title',
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Issued', 'Issued'), ('Returned', 'Returned'), ('Avaliable To issue', 'Avaliable To Issue'), ('Lost', 'Lost'), ('Damaged', 'Damaged')], max_length=100)),
                ('book_isntance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookstructure')),
            ],
        ),
        migrations.AddField(
            model_name='issuebook',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.bookcopy'),
        ),
    ]
