# Generated by Django 5.2.1 on 2025-06-03 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_bookstructure_count_remove_issuebook_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='book_isntance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.bookstructure'),
        ),
    ]
