# Generated by Django 5.2.1 on 2025-06-03 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_bookcopy_book_isntance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuebook',
            name='Price',
        ),
    ]
