# Generated by Django 5.2.1 on 2025-06-03 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_issuebook_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='book_isntance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookstructure'),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookcopy'),
        ),
    ]
