# Generated by Django 5.2.1 on 2025-06-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_bookcopy_book_isntance_alter_issuebook_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcopy',
            name='copy_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='status',
            field=models.CharField(choices=[('Issued', 'Issued'), ('Returned', 'Returned'), ('Available To issue', 'Available To Issue'), ('Lost', 'Lost'), ('Damaged', 'Damaged')], max_length=100),
        ),
    ]
