# Generated by Django 5.2.1 on 2025-06-03 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_bookcopy_copy_number_alter_bookcopy_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookcopy',
            old_name='book_isntance',
            new_name='book_instance',
        ),
    ]
