# Generated by Django 5.2.1 on 2025-06-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_rename_book_isntance_bookcopy_book_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='status',
            field=models.CharField(choices=[('Issued', 'Issued'), ('Returned', 'Returned'), ('Available To issue', 'Available To Issue'), ('Unavailable', 'Unavailable'), ('Lost', 'Lost'), ('Damaged', 'Damaged')], max_length=100),
        ),
    ]
