# Generated by Django 5.2.1 on 2025-06-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_bookcopy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='returned_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
