# Generated by Django 5.2.1 on 2025-06-23 10:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_issuebook_returned_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookstructure',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='bookstructure',
            old_name='Edition',
            new_name='edition',
        ),
        migrations.RenameField(
            model_name='bookstructure',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='bookstructure',
            old_name='Publication_date',
            new_name='publication_date',
        ),
        migrations.RenameField(
            model_name='bookstructure',
            old_name='Publisher',
            new_name='publisher',
        ),
        migrations.RenameField(
            model_name='bookstructure',
            old_name='Title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='bookstructure',
            name='Subject',
        ),
        migrations.RemoveField(
            model_name='bookstructure',
            name='keyword',
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bookstructure',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bookstructure',
            name='genre',
            field=models.CharField(default='unknown', help_text='genre of the book', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookstructure',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bookstructure',
            name='subject',
            field=models.TextField(default='unknown', help_text='summary of the book'),
            preserve_default=False,
        ),
    ]
