# Generated by Django 5.2.1 on 2025-06-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_rename_author_bookstructure_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bookstructure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bookstructure',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
