# Generated by Django 5.2.1 on 2025-06-23 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_bookcopy_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuebook',
            old_name='Issue_date',
            new_name='issue_date',
        ),
        migrations.RenameField(
            model_name='issuebook',
            old_name='Return_date',
            new_name='return_date',
        ),
    ]
