# Generated by Django 5.2.1 on 2025-05-30 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_customercreate_delete_customercreateform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customercreate',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='customercreate',
            old_name='Date_joined',
            new_name='date_joined',
        ),
        migrations.RenameField(
            model_name='customercreate',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customercreate',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customercreate',
            old_name='Phone',
            new_name='phone',
        ),
    ]
