# Generated by Django 5.2.1 on 2025-05-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_alter_customercreate_age_alter_customercreate_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercreate',
            name='username',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
