# Generated by Django 5.2.1 on 2025-06-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_customercreate_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercreate',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_user_pic.jpg', null=True, upload_to=''),
        ),
    ]
