# Generated by Django 5.2.1 on 2025-06-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_customercreate_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercreate',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
