# Generated by Django 5.2.1 on 2025-06-24 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_remove_customercreate_name_customercreate_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercreate',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customercreate',
            name='username',
        ),
    ]
