# Generated by Django 5.2.1 on 2025-06-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sub_admins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subadmin',
            name='permissions',
            field=models.ManyToManyField(to='auth.permission'),
        ),
    ]
