# Generated by Django 5.2.1 on 2025-06-24 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_admins', '0002_subadmin_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subadmin',
            options={'permissions': [('ReadBook', 'can read book'), ('UpdateBook', 'can update book'), ('DeleteBook', 'can delete book')], 'verbose_name': 'Sub Admin', 'verbose_name_plural': 'Sub Admins'},
        ),
    ]
